Тест 1 "The Bag of Words representation"
----------------------------------------


Работа с с возможностями работы над текстом

In [96]:
from sklearn.feature_extraction.text import CountVectorizer
import numpy as np

Создаем векторизатор, что бы преобразовать набор документов в вектора числовых признаков. 

In [105]:
#vectorizer = CountVectorizer(ngram_range=(1, 2, 3), token_pattern=r'\b\w+\b', min_df=1)
vectorizer = CountVectorizer(min_df=1)
vectorizer

CountVectorizer(analyzer=u'word', binary=False, decode_error=u'strict',
        dtype=<type 'numpy.int64'>, encoding=u'utf-8', input=u'content',
        lowercase=True, max_df=1.0, max_features=None, min_df=1,
        ngram_range=(1, 1), preprocessor=None, stop_words=None,
        strip_accents=None, token_pattern=u'(?u)\\b\\w\\w+\\b',
        tokenizer=None, vocabulary=None)

In [106]:
words = (['this', 'is', 'text', 'document', 'to', 'analyze'])

analyze = vectorizer.build_analyzer()
res = analyze("This is a text document to analyze.")

[u'this' u'is']


In [1]:
corpus = [
    'This is the first document.',
    'This is the second second document.',
    'And the third one.',
    'Is this the first document?'
]

X = vectorizer.fit_transform(corpus)

print X
print X.toarray()

names = ([
        'and', 
        'document', 
        'first', 
        'is', 
        'one',
        'second', 
        'the', 
        'third',
        'this'
    ])

vectorizer.get_feature_names() == names

NameError: name 'vectorizer' is not defined

In [107]:
print "X (array):\n", X.toarray()

vectorizer.vocabulary_.get('document')

  (0, 8)	1
  (0, 3)	1
  (0, 6)	1
  (0, 2)	1
  (0, 1)	1
  (1, 8)	1
  (1, 3)	1
  (1, 6)	1
  (1, 1)	1
  (1, 5)	2
  (2, 6)	1
  (2, 0)	1
  (2, 7)	1
  (2, 4)	1
  (3, 8)	1
  (3, 3)	1
  (3, 6)	1
  (3, 2)	1
  (3, 1)	1
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]
X (array):
[[0 1 1 1 0 0 1 0 1]
 [0 1 0 1 0 2 1 0 1]
 [1 0 0 0 1 0 1 1 0]
 [0 1 1 1 0 0 1 0 1]]


1

In [100]:
vectorizer.transform(['Something completely new.']).toarray()

array([[0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [111]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer2 = TfidfVectorizer(min_df=1)
print vectorizer2.fit_transform(corpus)

  (0, 1)	0.438776742859
  (0, 2)	0.541976569726
  (0, 6)	0.358728738248
  (0, 3)	0.438776742859
  (0, 8)	0.438776742859
  (1, 5)	0.853225736145
  (1, 1)	0.272301467523
  (1, 6)	0.222624292325
  (1, 3)	0.272301467523
  (1, 8)	0.272301467523
  (2, 4)	0.552805319991
  (2, 7)	0.552805319991
  (2, 0)	0.552805319991
  (2, 6)	0.28847674875
  (3, 1)	0.438776742859
  (3, 2)	0.541976569726
  (3, 6)	0.358728738248
  (3, 3)	0.438776742859
  (3, 8)	0.438776742859


In [120]:
ngram_vectorizer = CountVectorizer(analyzer='char_wb', ngram_range=(5, 5), min_df=1)
print ngram_vectorizer.fit_transform(['jumpy fox'])
ngram_vectorizer.get_feature_names() == (
    [' fox ', ' jump', 'jumpy', 'umpy '])      

  (0, 1)	1
  (0, 2)	1
  (0, 3)	1
  (0, 0)	1


True

In [117]:
ngram_vectorizer = CountVectorizer(analyzer='char', ngram_range=(5, 5), min_df=1)
ngram_vectorizer.fit_transform(['jumpy fox'])
                               


ngram_vectorizer.get_feature_names() == (
    ['jumpy', 'mpy f', 'py fo', 'umpy ', 'y fox'])

True